# Generated by Django 5.1.6 on 2025-03-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_citizenscharter_feedbackclassification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceExcellenceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_section', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('survey_date', models.DateField()),
                ('staff_first_name', models.CharField(max_length=100)),
                ('staff_last_name', models.CharField(max_length=100)),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (0, 'N/A')])),
                ('timeframe_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (0, 'N/A')])),
                ('prompt_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (0, 'N/A')])),
                ('polite_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (0, 'N/A')])),
                ('sensitive_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (0, 'N/A')])),
                ('dressed_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (0, 'N/A')])),
                ('facility_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (0, 'N/A')])),
                ('quality_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')])),
                ('comments', models.TextField(blank=True, null=True)),
                ('respondent_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('respondent_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_type', models.CharField(blank=True, choices=[('internal', 'Internal Client'), ('external', 'External Client')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
