# Generated by Django 5.1.6 on 2025-03-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_serviceexcellencefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallfeedback',
            name='equal_treatment',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='overallfeedback',
            name='satisfaction',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='admitting_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='billing_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='cashier_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='doctor_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='food_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='janitor_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='lab_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='midwife_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='nurse_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='pharmacy_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='radiology_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='records_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='security_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='staffrating',
            name='social_rating',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
    ]
