# Generated by Django 5.1.6 on 2025-03-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_overallfeedback_equal_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceexcellencefeedback',
            name='staff_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
