# Generated by Django 5.1.6 on 2025-03-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_serviceexcellencefeedback_staff_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerating',
            name='patient_interaction_1',
            field=models.IntegerField(choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], default=3),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='patient_interaction_2',
            field=models.IntegerField(choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], default=3),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='patient_interaction_3',
            field=models.IntegerField(choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], default=3),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='patient_interaction_4',
            field=models.IntegerField(choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], default=3),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='payment_fairness',
            field=models.IntegerField(choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], default=3),
        ),
    ]
