# Generated by Django 5.1.6 on 2025-03-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicerating_patient_interaction_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerating',
            name='payment_fairness',
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='patient_interaction_1',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='patient_interaction_2',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='patient_interaction_3',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='patient_interaction_4',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
    ]
