# Generated by Django 5.1.6 on 2025-03-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_servicerating_payment_fairness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerating',
            name='bathroom_cleanliness',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='patient_room_comfort',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='payment_fairness',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='transaction_ease',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='waiting_area_comfort',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='condition_explanation',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='information_accessibility',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='procedure_explanation',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='process_compliance',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='transaction_time',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='treatment_options',
            field=models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True),
        ),
    ]
