# Generated by Django 5.1.6 on 2025-03-07 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_servicerating_bathroom_cleanliness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_area_comfort', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('bathroom_cleanliness', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('patient_room_comfort', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('transaction_ease', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('process_compliance', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('information_accessibility', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('transaction_time', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_rating', to='core.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInteractionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_explanation', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('cultural_consideration', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('treatment_choice', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('service_delivery', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('payment_fairness', models.IntegerField(blank=True, choices=[(5, 'Lubos na Sumasang-ayon'), (4, 'Sumasang-ayon'), (3, 'Medyo Sumasang-ayon'), (2, 'Hindi Sumasang-ayon'), (1, 'Lubos na Hindi Sumasang-ayon')], null=True)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_interaction_rating', to='core.respondent')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceRating',
        ),
    ]
